### ISSUE TITLE
`description` should accept file input similar to how `name` works

### ISSUE THREAD

**Issue by aegershman** [aegershman/pivotal-tracker-resource#4]
self explanatory

```yaml
- put: tracker
  params:
    name: $NAME_FILE
    name_file: path/to/name/file
    description: $DESCRIPTION_FILE
    description_file: path/to/description/file
```
